name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: InstallingDependencies
        run: |
          ./requirements_ubuntu.sh

      - name: Building
        run: | 
          ./build.sh

      - name: UploadingArtifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Distributive
          path: |
            lib
            bin